"""empty message

Revision ID: 6c5658839a8a
Revises: a7b9b4816c9a
Create Date: 2021-02-21 16:13:19.300690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c5658839a8a"
down_revision = "a7b9b4816c9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("created_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "created_date")
    # ### end Alembic commands ###
